sudo: required
services:
  - docker

before_install:
  - docker build -t amitabc75/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true amitabc75/react-test npm test

after_success:
  - docker build -t amitabc75/multi-aclient ./client
  - docker build -t amitabc75/multi-nginx ./nginx
  - docker build -t amitabc75/multi-server ./server
  - docker build -t amitabc75/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker
  - docker push amitabc75/multi-nginx
  - docker push amitabc75/multi-aclient
  - docker push amitabc75/multi-server
  - docker push amitabc75/multi-worker
